p1ll-so-h1gh/Pillanner

- Pillanner/Model/DataManager.swift
> userdata, datamanger 합침

- Pillanner/Calendar/CalendarModel.swift
- Pillanner/Calendar/CalendarViewController.swift
- Pillanner/Calendar/CheckPillCell.swift
리팩토링도 살짝 했습니당 (레이첼 코드도 참고해서 살짝 수정ㅎ)
> [Chore] chevron 추가 및 셀 수정

- Pillanner.xcodeproj/project.pbxproj
- Pillanner/AppDelegate.swift
- Pillanner/Info.plist
- Pillanner/SceneDelegate.swift
- Pillanner/SignUp/LoginVC_NAVER_Login.swift
- Pillanner/SignUp/LoginViewController.swift
좀 더 간단하게 해보려다가 계속 안돼서 일단 Alamofire 활용해서 처리해놨습니다
> [Feat] 네이버 api 세팅 및 firebase 연동

- Pillanner/Cell/DeadlineCalendar/CalendarView.swift
- Pillanner/Cell/DueDateCell.swift
- Pillanner/InitialSetUp/InitialSetUpViewController.swift
- Pillanner/UserMain/PillAddMainViewController.swift
- Pillanner/UserMain/PillEditViewController.swift
DueDateCell의 캘린더 날짜값 데이터 delegate 패턴으로 연결
> [Fix]custom calendar delegate

- Pillanner.xcodeproj/project.pbxproj
- Pillanner/UserMain/Setting/PrivacyPolicyViewController.swift
- Pillanner/UserMain/Setting/TermsofUseViewController.swift
> 개인정보처리방침, 이용약관 부분 뷰 수정 및 내용 수정

- Pillanner.xcodeproj/project.pbxproj
- Pillanner/AppDelegate.swift
- Pillanner/Info.plist
- Pillanner/NotificationHelper.swift
더미데이터로 앱 상태에 따른 알림 테스트 완료
firebase에서 푸시 알림 가능 (apple developer - push notifications에서도 가능할 듯)
DosageAddVC에서 알람토글 버튼에 따라서 알람 활성화 여부 관련 로직 고민중
> [Feat] 복용시간 및 만료일 알림 추가

- Pillanner.xcodeproj/project.pbxproj
- Pillanner/DosageAddViewController.swift
- Pillanner/InitialSetUp/InitialSetUpViewController.swift
DosageAddViewController 뷰 버튼 수정했습니다
> DosageAddViewController UI 수정

- Pillanner/Calendar/CalendarViewController.swift
- Pillanner/Model/DataManager.swift
- Pillanner/Model/UserData.swift
캘린더에서 셀 눌렀을 때, firebase에 저장 로직 수정
> [Fix]takenpill 저장 datamanager 수정

- Pillanner/DosageAddViewController.swift
- Pillanner/Model/DataManager.swift
- Pillanner/Model/UserData.swift
- Pillanner/NotificationHelper.swift
- Pillanner/UserMain/PillAddMainViewController.swift
- Pillanner/UserMain/PillEditViewController.swift
- Pillanner/UserMain/PillListCollectionViewCell.swift
- Pillanner/UserMain/UserMainViewController.swift
1. dosage 데이터 타입 String으로 전반적인 수정 완료
2. MainUserUI 하루 달성률만 보이도록 수정
> [Fix] MainUI 수정 및 데이터 타입 변경

- Pillanner.xcodeproj/project.pbxproj
- Pillanner/DosageAddViewController.swift
- Pillanner/Model/UserData.swift
- Pillanner/UserMain/PillAddMainViewController.swift
- Pillanner/UserMain/PillEditViewController.swift
- Pillanner/UserMain/PillListCollectionViewCell.swift
DosageAddViewController에서 시간과 복용량을 선택하고, 저장하기 버튼을 눌렀을 때 데이터를 반환하도록만 구성했습니다 
아래 내용을 정리했는데, 이후에 UI 업데이트 부분도 게속 고민해보겠습니다
- 데이터 반환 메커니즘: 사용자가 "저장하기" 버튼을 누르면, 입력한 데이터는 DosageAddDelegate 프로토콜을 통해 반환
- 프로토콜에 포함되는 메서드 
updateAlarmStatus(isOn: Bool): 알람의 ON/OFF 상태를 전달
updateTimeData(time: String): 사용자가 선택한 복용 시간을 전달
updateDosageInfo(dosage: String, unit: String): 복용량과 그 단위를 전달
- 프로토콜 정의 및 적용: DosageAddDelegate 프로토콜을 정의하여, DosageAddViewController와 데이터를 주고받을 대상 명시
- PillAddMainViewController/PillEditViewController 에서 DosageAddDelegate 프로토콜 채택
- 데이터 수신 및 저장: updateAlarmStatus(isOn:), updateTimeData(time:), updateDosageInfo(dosage:unit:) 메서드를 구현하여, 복용량 관련 데이터를 수신하고 내부 변수에 저장, 이 데이터는 추후 UI 업데이트에 사용
- alarmStatus: 사용자가 설정한 알람의 상태를 저장
- timeData: 사용자가 선택한 복용 시간을 문자열 형태로 저장
- dosage: 사용자가 입력한 복용량을 저장
- …
> DosageAddViewController  데이터를 저장하고 관리

- Pillanner/AppDelegate.swift
- Pillanner/Calendar/CalendarViewController.swift
- Pillanner/DosageAddViewController.swift
- Pillanner/Model/DataManager.swift
- Pillanner/Model/UserData.swift
- Pillanner/NotificationHelper.swift
- Pillanner/UserMain/PillAddMainViewController.swift
- Pillanner/UserMain/PillEditViewController.swift
- Pillanner/UserMain/UserMainViewController.swift
- 캘린더 셀 선택 상태 유지
- 알람 상태에 따른 알림 보내기(보완 필요)
> [Chore] 알림 여부 관련 작업

- Pillanner/Model/DataManager.swift
- Pillanner/Model/UserData.swift
- Pillanner/SceneDelegate.swift
- Pillanner/SignUp/CustomLaunchScreenViewController.swift
- Pillanner/SignUp/LoginVC_APPLE_Login.swift
- Pillanner/SignUp/LoginVC_KAKAO_Login.swift
- Pillanner/SignUp/LoginVC_NAVER_Login.swift
- Pillanner/SignUp/LoginViewController.swift
- Pillanner/SignUp/SNSLoginViewController.swift
- Pillanner/SignUp/SignUpVC_Extension.swift
- Pillanner/UserMain/PillListCollectionViewCell.swift
- Pillanner/UserMain/UserMainViewController.swift
로그아웃 코드 전체 수정
DataManager 회원가입 메서드 수정
UserData 구조체에 회원가입 경로 추가
SceneDelegate 수정 ( 초기 화면 분기처리 )
커스텀런치스크린뷰 분기처리 수정
소셜로그인 시 UserDefault 에 데이터 저장
일반로그인 로그인로직 수정
꽤나 바뀐 부분들이 많은 것 같으니,,, 꼼꼼히 확인해보시길 바랍니다.
> 로그인 - 로그아웃 전체 수정

- Pillanner.xcodeproj/project.pbxproj
- Pillanner/Calendar/CalendarViewController.swift
- Pillanner/Model/Attainment.swift
- Pillanner/UserMain/UserMainViewController.swift
1. 캘린더에서 그날의 pillList 가져옴
2. pill복용 테이블 셀 선택 시 복용에 대한 업데이트 호출
3. attainment 클래스에서 계산
4. 계산한 값 메인에 연결해 달성률 보여주기
> [Chore] 달성률 로직 완료

- Pillanner/SignUp/CustomLaunchScreenViewController.swift
- Pillanner/SignUp/LoginViewController.swift
> [Fix] CustomLaunchScreenVC credential 부분 수정

- Pillanner/InitialSetUp/InitialSetupEndViewController.swift
- Pillanner/InitialSetUp/InitialSetupStartViewController.swift
- Pillanner/SceneDelegate.swift
- Pillanner/SignUp/CustomLaunchScreenViewController.swift
- Pillanner/SignUp/SNSLoginViewController.swift
- Pillanner/SignUp/SignUpVC_Extension.swift
[Fix] SignUp
기존 : 회원가입 -> 로그인 -> 메인뷰컨
변경 : 회원가입 -> 이니셜셋업 -> 메인뷰컨
로그인 -> 메인뷰컨
> [fix] 회원가입 시 이니셜셋업뷰컨트롤러로 넘어가도록 수정.

- Pillanner/Model/Attainment.swift
- Pillanner/TabBarController.swift
- Pillanner/UserMain/UserMainViewController.swift
더미데이터로 테스트 결과 달성률 계산 X
수정 구현
attainment를 탭바쪽에 두어 CalendarVC와 MainUserVC 중재자 역할로 둠
-> 더미 데이터로 실험해본 결과 구현됨
이후 구현
Attainment 클래스에 타이머를 두어 날짜 바뀔 때 리셋시켜 달성률 계산하도록 구성
> [Fix]-달성률 수정

- Pillanner.xcodeproj/project.pbxproj
- Pillanner/Find_ID_PW/FindIDVC_Extension.swift
- Pillanner/Find_ID_PW/FindIDViewController.swift
- Pillanner/Find_ID_PW/FindPWViewController.swift
- Pillanner/Model/DataManager.swift
- Pillanner/SignUp/CustomLaunchScreenViewController.swift
- Pillanner/SignUp/SignUpVC_Extension.swift
- Pillanner/UserMain/Setting/UserInfoView.swift
[Chore] ID/PW 찾기 기능 추가
추가 변경사항 : CustomLaunchScreenVC, UserInfoView 일부 코드 수정
* Datamanager - 아이디찾기 메서드 추가, readUserData 메서드 수정(에러핸들링 처리)
> [Chore] ID/PW 찾기 기능 추가

- Pillanner/Model/DataManager.swift
- Pillanner/NotificationHelper.swift
기존 UserDefaults에서 UID 값을 받아 약 데이터 가져옴 -> FireStore에서 직접 가져옴
카일의 도움으로 이슈 해결,,(addSnapshotListener :  Firebase Firestore의 컬렉션에 대한 실시간 업데이트를 감시하고 가져옴)
> [Chore] 알림 로직 수정 및 테스트

- Pillanner/Calendar/CalendarViewController.swift
- Pillanner/Model/Attainment.swift
- Pillanner/Model/DataManager.swift
현재 달성률 계산 가능!
앞으로 개선해야할 점
1. 약이 중간에 추가될 경우 totalEvent의 업데이트 필요
2. 당일 먹을 약을 삭제할 경우, totalEvent 업데이트 필요
3. 날이 변경되는 시점을 알려 리셋하는 기능 필요
> [Fix]-달성률 2차 수정

- Pillanner/Calendar/CheckPillCell.swift
- Pillanner/InitialSetUp/InitialSetUpViewController.swift
- Pillanner/UserMain/PillAddMainViewController.swift
- Pillanner/UserMain/PillListCollectionViewCell.swift
initial setup 화면에서 사용되는 Cell 들의 delegate 설정이 누락되어 있어서 연결함
> [FEAT] InitialSetUpViewController 기능 추가(2차, 테스트 X)

- Pillanner/Extension/UIColor+Extension.swift
- Pillanner/UserMain/Setting/NoticeViewController.swift
- Pillanner/UserMain/Setting/PrivacyPolicyViewController.swift
- Pillanner/UserMain/Setting/TermsofUseViewController.swift
- Pillanner/UserMain/Setting/UserSettingViewController.swift
공지사항 / 버전정보 수정했습니다
공지사항 부분은 내용 임의로 넣었는데, 한 번 검토해주시고 
다른 추가사항있다면 이야기해주세요!
> SettingVC 공지사항 / 버전정보 수정

- Pillanner/Calendar/CalendarViewController.swift
우선 UserDefaults에 IndexPath를 저장해서 앱이 재실행되어도 셀이 눌려있게 해놨습니다.
문제로는 아마 아이디가 달라지면 index 저장된 값으로 index 순서에 따라 셀이 눌려있을 것,,
> [Chore] 캘린더 셀 선택 문제 일부 해결

- Pillanner/Beginning/SignUp/SignUpVC_Extension.swift
- Pillanner/Beginning/SignUp/SignUpViewController.swift
- Pillanner/MainView/UserStatus/Setting/UserSettingViewController.swift
회원가입 백 버튼 수정 완료하고 알림 수신 여부에 따라 설정 화면에 들어갔을 때 상태에 맞게 보여지게 했습니다.
네이버 로그인 부분은 네이버 측에서 검수 진행중입니다.
> [Chore] 회원가입 백 버튼수정 및 알림 수신 활성화

- Pillanner/Cell/IntakeSettingCell.swift
섭취 횟수를 넣을때마다 테이블이 이제 늘어나게 됩니다...! 히히
> [Fix] intrinsic 문제 해결

- Pillanner.xcodeproj/project.pbxproj
- Pillanner/MainView/CalendarView/CalendarVC_Extension.swift
- Pillanner/MainView/CalendarView/CalendarViewController.swift
선택된 셀들은 24시 이후에 초기화되게 하고  코드가 복잡해서 약간의 리팩토링을 했습니다.
> [Chore] 캘린더 셀 관련 수정 및 리팩토링

- Pillanner/Global/Feature/DataManager.swift
- Pillanner/MainView/UserStatus/UserMainViewController.swift
복용약 삭제 시 달셩률 안그려지는 현상 해결
달성률 계산 시 오늘 먹을 전체 약 개수 계산 수정
> [Fix] 달성률 로직 수정 완료

- Pillanner/Beginning/SignUp/SignUpViewController.swift
- README.md
> [chore] README.md 파일 수정(배너 이미지 삽입, 어플리케이션 다운로드 링크 삽입, 팀원 설명, 기술스택 표 작성)
